### ISSUE TITLE
Experimental Kotlin Jupyter Kernal `%javascript` magic support

### ISSUE THREAD

**Issue by yidafu** [Kotlin/kotlin-jupyter-libraries#328]
Hi guys!

[kotlin-jupyter-js](https://github.com/yidafu/kotlin-jupyter-js/) is a library to support `%javascript`/`%typescript`/`%jsx` magic. 

In some cases, we want create **interactive** charts or **3d** charts, which only javascript can do. I create a library to support executing javascript code in kotlin jupyter kernal, so we could using javascript to render our kotlin data.

See more usage read [README](https://github.com/yidafu/kotlin-jupyter-js/blob/main/README.md) file.

#### JS Sample

First declare a variable in cell

```kotlin
// value define in kotlin world
val kNumber = 233
```
then, add a cell with %js magic

```js
%js
// using `kNumber` in js workd
import { kNumber } from '@jupyter'

getCellRoot().innerHTML = `<h1>${kNumber}</h1>`
```

![image](https://github.com/yidafu/kotlin-jupyter-js/assets/22773923/cd1d84d3-7dcc-4f0f-8a3e-50300e4f7e4c)

## React Example

preview cell declare a variable in cell
```kotlin
val foo = "foo from kotlin word";
```
Export your Components

```jsx
%jsx

import { foo } from "@jupyter";

export default function App() {
    return <h1>{foo}</h1>
}
```

![image](https://github.com/yidafu/kotlin-jupyter-js/assets/22773923/c8902c7e-813d-41b3-be6b-b0ee192e890b)

### Full examples

<https://yidafu.github.io/kotlin-jupyter-js/examples/js-magic.html>

<https://yidafu.github.io/kotlin-jupyter-js/examples/girls-last-tour.html>

**Comment by ileasile** [comment]
Wow! It looks really cool! Sorry for the delay in getting back to you, I was a little busy last few days.
